# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wisp Hill - Glow of Geekery
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blazing vault of tech wisdom where I spark what I’ve learned and ignite ideas to share with you!
repository: https://github.com/wisphill/blog
baseurl: /blog  # the subpath of your site, e.g. /blog
url: https://wisphill.github.io  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Phil Nguyễn
email: fizz.uet@gmail.com

collections_dir: yuu_academy

collections:
  aws_analytic:
    output: true
    test: 1
    permalink: /:collection/:path/
  aws_vpc:
    output: true
    permalink: /:collection/:path/
  aws_cf:
    output: true
    permalink: /:collection/:path/
  aws_iam:
    output: true
    permalink: /:collection/:path/
  aws_cloudwatch_monitoring:
    output: true
    permalink: /:collection/:path/
  aws_db:
    output: true
    permalink: /:collection/:path/
  aws_disaster_recovery:
    output: true
    permalink: /:collection/:path/
  aws_ec2:
    output: true
    permalink: /:collection/:path/
  aws_guard_firewall:
    output: true
    permalink: /:collection/:path/
  aws_machine_learning:
    output: true
    permalink: /:collection/:path/
  aws_rds:
    output: true
    permalink: /:collection/:path/
  aws_route53:
    output: true
    permalink: /:collection/:path/
  aws_s3:
    output: true
    permalink: /:collection/:path/
  aws_serverless:
    output: true
    permalink: /:collection/:path/
  aws_sqs:
    output: true
    permalink: /:collection/:path/
  aws_storage:
    output: true
    permalink: /:collection/:path/
  aws_asg:
    output: true
    permalink: /:collection/:path/
  aws_container:
    output: true
    permalink: /:collection/:path/
  programming:
    output: true
    permalink: /:collection/:path/

social:
  - service: github
    username: wisphill
    link: https://github.com/wisphill
  - service: linkedin
    username: wisphill
    link: https://linkedin.com/in/wisphill/
  - service: youtube
    username: yuu.orenji
    link: https://youtube.com/@yuu.orenji
  - service: deviantart
    username: yuulya
    link: https://deviantart.com/yuulya
  - service: twitter
    username: wisphill
    link: https://twitter.com/wisphill

# Plugins
gems:
  - jekyll-seo-tag
